name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew test
    
    # The test reports are generated in app/build/reports/tests
    # Source: https://developer.android.com/studio/test/command-line
    - name: Collect Debug Test Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: TestReportDebug
        path: ./app/build/reports/tests/testDebugUnitTest
        retention-days: 30
        
    - name: Collect Release Test Report 
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: TestReportRelease
        path: ./app/build/reports/tests/testReleaseUnitTest
        retention-days: 30
